### Problem: Describe the shape, size, and dimensions of the matrix

In [1]:
import numpy as np
# Create a matrix
# This matrix is of 3 rows and 4 columns shape
matrix = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [2]:
# View the number of rows and columns
matrix.shape

(3, 4)

In [3]:
# View number of elements (rows * columns)
matrix.size

12

### Applying Operations to Elements

In [4]:
import numpy as np
# Create a Matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [6]:
# Create a function that adds 100 to something
def add100(x):
    return 100 + x

# Create a Lambda Function to add 100 to something
# Lambda is an anonymous function
add_100 = lambda i : i + 100

print(add_100(1))

101


In [7]:
print(add_100(1))

101


In [8]:
# Create a vectorized function
'''
NumPy's vectorize class converts a function into a function that can apply to all elements in an array or slice of an array.
'''
# From the above statement, we can use vectorized_add_100 as a function after we compile the following line of code.
vectorized_add_100 = np.vectorize(add_100)

In [9]:
# Apply function to all elements in a matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [10]:
# Add 100 to all elements using broadcasting process
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [11]:
# Return maximum element
np.max(matrix)

9

In [12]:
# Return the minimum element
np.min(matrix)

1

In [14]:
# Find maximum element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [15]:
# Find maximum element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

### Calculating the Average, Variance, and Standard Deviation

In [16]:
import numpy as np
# Create a Matix
matrix = np.matrix([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

In [17]:
# Return the mean
np.mean(matrix)

5.0

In [18]:
# Return the variance
np.var(matrix)

6.666666666666667

In [19]:
# Return the standard deviation
np.std(matrix)

2.581988897471611

In [20]:
# Find the mean value in each column
np.mean(matrix, axis=0)

matrix([[4., 5., 6.]])

In [21]:
# Find the mean value in each row
np.mean(matrix, axis=1)

matrix([[2.],
        [5.],
        [8.]])

### Reshape NumPy Arrays

In [22]:
import numpy as np
# Create a 4x3 matrix
matrix = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9],
                  [10, 11, 12]])

# Reshape matrix into 2x6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])